const MAKELINE_BOX_WIDTH = 65;
const MAKELINE_BOX_HEIGHT = 75;
const MAKELINE_GAP = 0.25;
const MAKELINE_BOX_MARGIN = 0.03;
const MOD_PIZZA_RED = "#C4122F";
const MOD_PIZZA_DARK_RED = "#8B0E04";
const MOD_PIZZA_OFF_WHITE = "#F3F2EF";
export {
  MAKELINE_BOX_WIDTH,
  MAKELINE_BOX_HEIGHT,
  MAKELINE_BOX_MARGIN,
  MAKELINE_GAP,
  MOD_PIZZA_RED,
  MOD_PIZZA_DARK_RED,
  MOD_PIZZA_OFF_WHITE,
};
