const MAKELINE_BOX_WIDTH = 65;
const MAKELINE_BOX_HEIGHT = 75;
const MAKELINE_GAP = 0.25;
const MAKELINE_BOX_MARGIN = 0.03;

export {
  MAKELINE_BOX_WIDTH,
  MAKELINE_BOX_HEIGHT,
  MAKELINE_BOX_MARGIN,
  MAKELINE_GAP,
};
